apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: nirbhava  # Ensure this matches your PV's namespace
spec:
  replicas: 1  # Number of replicas (pods)
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          args: ["--dbpath","/data/db"]
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: ""  # Set your MongoDB username here
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: ""  # Set your MongoDB password here
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 40Gi  # Storage size for each pod
        storageClassName: standard  # Define the storage class (adjust if needed)

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport-service
  namespace: nirbhava
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017          # External port to access the service
      targetPort: 27017    # Port on the MongoDB pods
      nodePort: 32000      # Port exposed on each Node (choose a port between 30000-32767)
